apiVersion: apps/v1
kind: Deployment
# set deploy name and labels
metadata:
  name: ftps
  labels:
    app  : ftps
    owner: qtamaril
spec:
  # with which pods will be work deploy
  selector:
    matchLabels:
       app: ftps
  # before starting new pods, all old ones will be deleted
  strategy:
    type: Recreate
  # create pods...
  template:
    metadata:
      labels: 
        app  : ftps
        owner: qtamaril
    spec:
      # ...based on image
      containers: 
      - name           : ftps
        image          : ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 10100
---
apiVersion: v1
kind: Service
# set service name and labels
metadata:
  name: ftps-svc
  labels:
    app  : ftps-svc
    owner: qtamaril
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.104
  # with which pods will be work service
  selector:
    app: ftps
  ports:
    - name      : port-ftps-1
      protocol  : TCP
      port      : 21 # port on LoadBalancer
      targetPort: 21 # port on pod
    - name      : port-ftps-2
      protocol  : TCP
      port      : 10100 # port on LoadBalancer
      targetPort: 10100 # port on pod