apiVersion: apps/v1
kind: Deployment
# set deploy name and labels
metadata:
  name: grafana
  labels:
    app  : grafana
    owner: qtamaril
spec:
  # with which pods will be work deploy
  selector:
    matchLabels:
       app: grafana
  # before starting new pods, all old ones will be deleted
  strategy:
    type: Recreate
  # create pods...
  template:
    metadata:
      labels: 
        app  : grafana
        owner: qtamaril
    spec:
      # ...based on image
      containers: 
      - name           : grafana
        image          : grafana
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
# set service name and labels
metadata:
  name: grafana-svc
  labels:
    app  : grafana-svc
    owner: qtamaril
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.105
  # with which pods will be work service
  selector:
    app: grafana
  ports:
    - name      : port-grafana
      protocol  : TCP
      port      : 3000 # port on LoadBalancer
      targetPort: 3000 # port on pod