# PersistentVolumeClaim is a request for storage by a user
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pv-claim
spec:
  # PersistentVolume name
  storageClassName: influxdb-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
# set deploy name and labels
metadata:
  name: influxdb
  labels:
    app  : influxdb
    owner: qtamaril
spec:
  # with which pods will be work deploy
  selector:
    matchLabels:
       app: influxdb
  # before starting new pods, all old ones will be deleted
  strategy:
    type: Recreate
  # create pods...
  template:
    metadata:
      labels: 
        app  : influxdb
        owner: qtamaril
    spec:
      # ...based on image
      containers:
      - name           : influxdb
        image          : influxdb
        imagePullPolicy: Never
        ports:
        - containerPort: 8086
        # with which toms will be work image
        volumeMounts:
        - name     : influxdb-storage
          mountPath: /var/lib
        - name     : dockersock
          mountPath: /var/run/docker.sock
      # create toms...
      volumes:
      - name: influxdb-storage
        # ...based on PersistentVolumeClaim
        persistentVolumeClaim:
          claimName: influxdb-pv-claim
        # ...based on docker sock
      - name: dockersock
        hostPath:
            path: /var/run/docker.sock
---
apiVersion: v1
kind: Service
# set service name and labels
metadata:
  name: influxdb-svc
  labels:
    app  : influxdb-svc
    owner: qtamaril
spec:
  type: ClusterIP
  # with which pods will be work service
  selector:
    app: influxdb
  ports:
  - name      : port-influxdb
    protocol  : TCP
    port      : 8086
    targetPort: 8086