apiVersion: apps/v1
kind: Deployment
# set deploy name and labels
metadata:
  name: nginx
  labels:
    app  : nginx
    owner: qtamaril
spec:
  # with which pods will be work deploy
  selector:
    matchLabels:
       app: nginx
  # before starting new pods, all old ones will be deleted
  strategy:
    type: Recreate
  # create pods...
  template:
    metadata:
      labels: 
        app  : nginx
        owner: qtamaril
    spec:
      # ...based on image
      containers: 
      - name           : nginx
        image          : nginx
        imagePullPolicy: Never
        ports:
        - containerPort: 443
        - containerPort: 80
        - containerPort: 22
---
apiVersion: v1
kind: Service
# set service name and labels
metadata:
  name: nginx-svc
  labels:
    app  : nginx-svc
    owner: qtamaril
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.101
  # with which pods will be work service
  selector:
    app: nginx
  ports:
    - name      : port-https
      protocol  : TCP
      port      : 443 # port on LoadBalancer
      targetPort: 443 # port on pod
    - name      : port-http
      protocol  : TCP
      port      : 80
      targetPort: 80
    - name      : port-ssh
      protocol  : TCP
      port      : 22  
      targetPort: 22