apiVersion: apps/v1
kind: Deployment
# set deploy name and labels
metadata:
  name: phpmyadmin
  labels:
    app  : phpmyadmin
    owner: qtamaril
spec:
  # with which pods will be work deploy
  selector:
    matchLabels:
       app: phpmyadmin
  # before starting new pods, all old ones will be deleted
  strategy:
    type: Recreate
  # create pods...
  template:
    metadata:
      labels: 
        app  : phpmyadmin
        owner: qtamaril
    spec:
      # ...based on image
      containers: 
      - name           : phpmyadmin
        image          : phpmyadmin
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
# set service name and labels
metadata:
  name: phpmyadmin-svc
  labels:
    app  : phpmyadmin-svc
    owner: qtamaril
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.102
  # with which pods will be work service
  selector:
    app: phpmyadmin
  ports:
    - name      : port-http
      protocol  : TCP
      port      : 5000 # port on LoadBalancer
      targetPort: 5000 # port on pod