apiVersion: apps/v1
kind: Deployment
# set deploy name and labels
metadata:
  name: wordpress
  labels:
    app  : wordpress
    owner: qtamaril
spec:
  # with which pods will be work deploy
  selector:
    matchLabels:
       app: wordpress
  # before starting new pods, all old ones will be deleted
  strategy:
    type: Recreate
  # create pods...
  template:
    metadata:
      labels: 
        app  : wordpress
        owner: qtamaril
    spec:
      # ...based on image
      containers: 
      - name           : wordpress
        image          : wordpress
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
---
apiVersion: v1
kind: Service
# set service name and labels
metadata:
  name: wordpress-svc
  labels:
    app  : wordpress-svc
    owner: qtamaril
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.103
  # with which pods will be work service
  selector:
    app: wordpress
  ports:
    - name      : port-wordpress
      protocol  : TCP
      port      : 5050 # port on LoadBalancer
      targetPort: 5050 # port on pod